import type {
  DashboardData,
  NatGatewayDetails,
  SubnetItem,
  ConnectionListResponse,
  TrafficResponse,
  SnatResponse,
  CostResponse,
  AlertItem,
  NetworkHealthResponse,
  SimulationStatus,
  ArchitectureResponse
} from '../types';

export const mockDashboard: DashboardData = {
  network_health: 98,
  gateway_status: 'Healthy',
  public_ip: '20.45.123.10',
  public_ips: ['20.45.123.10', '20.45.123.11'],
  active_connections: 1248,
  snat_utilization: 38.2,
  data_processed_gb: 284.6,
  monthly_cost: 45.66,
  region: 'East US',
  resource_group: 'rg-networking-prod',
  is_simulation_active: false,
  environment: 'DEMO / SIMULATED ENVIRONMENT',
};

export const mockNatGateway: NatGatewayDetails = {
  id: 'nat-gw-prod-eastus',
  name: 'nat-gw-prod-eastus',
  status: 'Healthy',
  region: 'East US',
  resource_group: 'rg-networking-prod',
  subscription_id: 'sub-azure-90214-prod',
  sku: 'Standard',
  zones: ['1', '2', '3'],
  idle_timeout_minutes: 4,
  tcp_reset_enabled: true,
  public_ips: ['20.45.123.10', '20.45.123.11'],
  attached_subnets_count: 4,
  attached_subnets: ['frontend-subnet', 'backend-subnet', 'database-subnet', 'aks-nodes-subnet'],
  current_throughput_mbps: 184.6,
  active_connections: 1248,
  snat_utilization_pct: 38.2,
  data_processed_gb: 284.6,
  created_date: '2025-11-14T08:30:00Z',
  environment: 'DEMO / SIMULATED',
};

export const mockSubnets: SubnetItem[] = [
  {
    id: 'snet-frontend',
    name: 'frontend-subnet',
    vnet_name: 'vnet-prod-eastus',
    cidr: '10.0.1.0/24',
    private_ip_range: '10.0.1.4 - 10.0.1.254',
    resources_count: 24,
    outbound_ip: '20.45.123.10',
    active_connections: 428,
    status: 'Healthy',
    description: 'Public-facing web applications & ingress proxies with dedicated egress NAT',
  },
  {
    id: 'snet-backend',
    name: 'backend-subnet',
    vnet_name: 'vnet-prod-eastus',
    cidr: '10.0.2.0/24',
    private_ip_range: '10.0.2.4 - 10.0.2.254',
    resources_count: 18,
    outbound_ip: '20.45.123.10',
    active_connections: 512,
    status: 'Healthy',
    description: 'Microservices API tier communicating with third-party payment & auth APIs',
  },
  {
    id: 'snet-database',
    name: 'database-subnet',
    vnet_name: 'vnet-prod-eastus',
    cidr: '10.0.3.0/24',
    private_ip_range: '10.0.3.4 - 10.0.3.254',
    resources_count: 8,
    outbound_ip: '20.45.123.10',
    active_connections: 308,
    status: 'Healthy',
    description: 'Managed databases & read replicas performing external backup syncs',
  },
  {
    id: 'snet-aks-nodes',
    name: 'aks-nodes-subnet',
    vnet_name: 'vnet-prod-eastus',
    cidr: '10.0.4.0/24',
    private_ip_range: '10.0.4.4 - 10.0.4.254',
    resources_count: 32,
    outbound_ip: '20.45.123.11',
    active_connections: 620,
    status: 'Healthy',
    description: 'Azure Kubernetes Service worker nodes pulling container images and telemetry',
  },
];

export const mockConnections: ConnectionListResponse = {
  total_connections: 1248,
  active_connections: 1190,
  failed_connections: 1,
  connections_per_minute: 420,
  avg_connection_duration_sec: 14.8,
  items: [
    {
      id: 'conn-1001',
      source_ip: '10.0.2.14',
      source_subnet: 'backend-subnet',
      destination_ip: '54.187.205.235',
      destination_host: 'api.stripe.com',
      protocol: 'TCP',
      destination_port: 443,
      snat_port: 49210,
      status: 'Established',
      bytes_transferred: 845200,
      duration_seconds: 18,
      timestamp: 'Just now',
    },
    {
      id: 'conn-1002',
      source_ip: '10.0.2.19',
      source_subnet: 'backend-subnet',
      destination_ip: '20.190.159.0',
      destination_host: 'login.microsoftonline.com',
      protocol: 'TCP',
      destination_port: 443,
      snat_port: 49211,
      status: 'Established',
      bytes_transferred: 124000,
      duration_seconds: 6,
      timestamp: '10s ago',
    },
    {
      id: 'conn-1003',
      source_ip: '10.0.4.31',
      source_subnet: 'aks-nodes-subnet',
      destination_ip: '140.82.113.4',
      destination_host: 'api.github.com',
      protocol: 'TCP',
      destination_port: 443,
      snat_port: 51402,
      status: 'Established',
      bytes_transferred: 458920,
      duration_seconds: 22,
      timestamp: '25s ago',
    },
    {
      id: 'conn-1004',
      source_ip: '10.0.1.8',
      source_subnet: 'frontend-subnet',
      destination_ip: '104.16.27.35',
      destination_host: 'registry.npmjs.org',
      protocol: 'TCP',
      destination_port: 443,
      snat_port: 52119,
      status: 'Closed',
      bytes_transferred: 3420000,
      duration_seconds: 45,
      timestamp: '1m ago',
    },
    {
      id: 'conn-1005',
      source_ip: '10.0.3.12',
      source_subnet: 'database-subnet',
      destination_ip: '52.239.144.18',
      destination_host: 'blob.core.windows.net',
      protocol: 'TCP',
      destination_port: 443,
      snat_port: 53001,
      status: 'Established',
      bytes_transferred: 18240000,
      duration_seconds: 120,
      timestamp: '2m ago',
    },
    {
      id: 'conn-1006',
      source_ip: '10.0.2.45',
      source_subnet: 'backend-subnet',
      destination_ip: '34.120.89.12',
      destination_host: 'api.sendgrid.com',
      protocol: 'TCP',
      destination_port: 587,
      snat_port: 53140,
      status: 'Closed',
      bytes_transferred: 32000,
      duration_seconds: 4,
      timestamp: '3m ago',
    },
    {
      id: 'conn-1007',
      source_ip: '10.0.4.15',
      source_subnet: 'aks-nodes-subnet',
      destination_ip: '52.84.162.77',
      destination_host: 'index.docker.io',
      protocol: 'TCP',
      destination_port: 443,
      snat_port: 53890,
      status: 'Established',
      bytes_transferred: 68400000,
      duration_seconds: 240,
      timestamp: '4m ago',
    },
    {
      id: 'conn-1008',
      source_ip: '10.0.1.22',
      source_subnet: 'frontend-subnet',
      destination_ip: '151.101.65.140',
      destination_host: 'api.datadoghq.com',
      protocol: 'TCP',
      destination_port: 443,
      snat_port: 54012,
      status: 'Time_Wait',
      bytes_transferred: 78500,
      duration_seconds: 3,
      timestamp: '5m ago',
    },
    {
      id: 'conn-1009',
      source_ip: '10.0.2.8',
      source_subnet: 'backend-subnet',
      destination_ip: '198.51.100.44',
      destination_host: 'legacy-partner-api.com',
      protocol: 'TCP',
      destination_port: 8443,
      snat_port: 54220,
      status: 'Failed',
      bytes_transferred: 0,
      duration_seconds: 30,
      timestamp: '8m ago',
    },
  ],
};

export const mockTraffic: TrafficResponse = {
  timeframe: '24h',
  total_data_processed_gb: 284.6,
  peak_throughput_mbps: 218.5,
  metrics: [
    { time: '00:00', traffic_mbps: 78.4, requests_per_min: 14200, connections: 780, data_processed_gb: 24.2 },
    { time: '04:00', traffic_mbps: 54.1, requests_per_min: 9800, connections: 540, data_processed_gb: 38.5 },
    { time: '08:00', traffic_mbps: 142.8, requests_per_min: 28600, connections: 1120, data_processed_gb: 78.0 },
    { time: '12:00', traffic_mbps: 196.2, requests_per_min: 41200, connections: 1450, data_processed_gb: 142.6 },
    { time: '16:00', traffic_mbps: 218.5, requests_per_min: 48900, connections: 1680, data_processed_gb: 210.4 },
    { time: '20:00', traffic_mbps: 164.2, requests_per_min: 34100, connections: 1310, data_processed_gb: 258.9 },
    { time: '24:00', traffic_mbps: 184.6, requests_per_min: 37800, connections: 1248, data_processed_gb: 284.6 },
  ],
  top_destinations: [
    { host: 'api.stripe.com', ip: '54.187.205.235', requests: 48200, category: 'Payment Gateway', percentage: 34.2 },
    { host: 'login.microsoftonline.com', ip: '20.190.159.0', requests: 36400, category: 'Identity & Entra ID', percentage: 25.8 },
    { host: 'blob.core.windows.net', ip: '52.239.144.18', requests: 24100, category: 'Storage Backups', percentage: 17.1 },
    { host: 'registry.npmjs.org', ip: '104.16.27.35', requests: 18500, category: 'Package Registry', percentage: 13.1 },
    { host: 'api.github.com', ip: '140.82.113.4', requests: 13800, category: 'CI/CD & Git Webhooks', percentage: 9.8 },
  ],
};

export const mockSnat: SnatResponse = {
  total_snat_ports: 129024,
  used_ports: 49287,
  available_ports: 79737,
  utilization_percentage: 38.2,
  port_allocation_rate_per_sec: 16.8,
  risk_level: 'LOW',
  failed_allocations_count: 0,
  public_ip_count: 2,
  ports_per_ip: 64512,
  history: [
    { time: '00:00', used_ports: 28400, available_ports: 100624, utilization_pct: 22.0 },
    { time: '04:00', used_ports: 21100, available_ports: 107924, utilization_pct: 16.4 },
    { time: '08:00', used_ports: 39500, available_ports: 89524, utilization_pct: 30.6 },
    { time: '12:00', used_ports: 47200, available_ports: 81824, utilization_pct: 36.6 },
    { time: '16:00', used_ports: 54100, available_ports: 74924, utilization_pct: 41.9 },
    { time: '20:00', used_ports: 44800, available_ports: 84224, utilization_pct: 34.7 },
    { time: '24:00', used_ports: 49287, available_ports: 79737, utilization_pct: 38.2 },
  ],
};

export const mockCost: CostResponse = {
  current_month_cost: 45.66,
  estimated_monthly_cost: 81.34,
  nat_gateway_hours: 410.0,
  data_processed_gb: 284.6,
  data_processing_cost: 12.81,
  gateway_cost: 18.45,
  currency: 'USD',
  breakdown: {
    gateway_hours: 410.0,
    gateway_rate_per_hour: 0.045,
    gateway_subtotal: 18.45,
    data_processed_gb: 284.6,
    data_rate_per_gb: 0.045,
    data_subtotal: 12.81,
    currency: 'USD',
    total: 45.66,
  },
  daily_trend: [
    { day: 'Day -6', gateway_cost: 1.08, data_cost: 1.46, total: 2.54 },
    { day: 'Day -5', gateway_cost: 1.08, data_cost: 1.62, total: 2.70 },
    { day: 'Day -4', gateway_cost: 1.08, data_cost: 1.87, total: 2.95 },
    { day: 'Day -3', gateway_cost: 1.08, data_cost: 2.06, total: 3.14 },
    { day: 'Day -2', gateway_cost: 1.08, data_cost: 1.81, total: 2.89 },
    { day: 'Yesterday', gateway_cost: 1.08, data_cost: 1.98, total: 3.06 },
    { day: 'Today', gateway_cost: 0.83, data_cost: 2.01, total: 2.84 },
  ],
  is_simulated: true,
};

export const mockAlerts: AlertItem[] = [
  {
    id: 'ALT-2041',
    alert_type: 'SNAT Port Utilization',
    severity: 'WARNING',
    title: 'SNAT Port Utilization Approaching Warning Threshold (38.2%)',
    description: 'Peak SNAT port utilization across frontend-subnet reached 49,287 ports. Headroom remains healthy with 79,737 ports free across 2 public IPs.',
    component: 'nat-gw-prod-eastus / frontend-subnet',
    timestamp: '12 minutes ago',
    status: 'ACTIVE',
  },
  {
    id: 'ALT-2040',
    alert_type: 'High Outbound Traffic',
    severity: 'INFO',
    title: 'Sustained Outbound Throughput Spike (184 Mbps)',
    description: 'Outbound bandwidth sustained above 150 Mbps for 10 minutes due to scheduled database snapshot export to Azure Blob Storage.',
    component: 'database-subnet',
    timestamp: '34 minutes ago',
    status: 'ACTIVE',
  },
  {
    id: 'ALT-2039',
    alert_type: 'Cost Threshold',
    severity: 'WARNING',
    title: 'Monthly NAT Gateway Spend Forecast Reached 65% of Budget',
    description: 'Current month accrued spend is $45.66 against target budget cap of $65.00 with 11 days remaining in cycle.',
    component: 'Cost Management',
    timestamp: '2 hours ago',
    status: 'ACTIVE',
  },
  {
    id: 'ALT-2038',
    alert_type: 'Gateway Health',
    severity: 'INFO',
    title: 'Availability Zone Health Check Verified',
    description: 'Zone redundancy health check completed. NAT Gateway instances are fully operational across Availability Zones 1, 2, and 3.',
    component: 'nat-gw-prod-eastus',
    timestamp: '5 hours ago',
    status: 'RESOLVED',
    resolved_at: '4 hours ago',
  },
  {
    id: 'ALT-2037',
    alert_type: 'Subnet Connectivity',
    severity: 'INFO',
    title: 'AKS Worker Node Subnet Egress Route Synchronized',
    description: 'Subnet aks-nodes-subnet route table verified with default route 0.0.0.0/0 next-hop mapped to NAT Gateway.',
    component: 'aks-nodes-subnet',
    timestamp: '1 day ago',
    status: 'RESOLVED',
    resolved_at: '1 day ago',
  },
];

export const mockNetworkHealth: NetworkHealthResponse = {
  overall_score: 98,
  status_label: 'Optimal',
  calculation_timestamp: new Date().toISOString(),
  factors: [
    {
      name: 'Gateway Availability & Fabric Health',
      score: 100,
      weight_pct: 35,
      status: 'Optimal',
      impact: 'Primary NAT translation fabric and zone redundancy check',
    },
    {
      name: 'SNAT Port Headroom & Allocation',
      score: 100,
      weight_pct: 25,
      status: 'Ample Port Capacity',
      impact: '38.2% total capacity utilized across public IPs',
    },
    {
      name: 'Connection Delivery & Drop Rate',
      score: 100,
      weight_pct: 20,
      status: '99.9% Success Rate',
      impact: '1 failed connections observed in current sample',
    },
    {
      name: 'Active Infrastructure Incidents',
      score: 90,
      weight_pct: 20,
      status: 'No Critical Incidents',
      impact: '3 unresolved telemetry alerts',
    },
  ],
  summary_message: 'All Azure NAT Gateway subnets operating with ideal SNAT headroom and deterministic IP egress.',
};

export const mockArchitecture: ArchitectureResponse = {
  vnet_name: 'vnet-prod-eastus',
  vnet_cidr: '10.0.0.0/16',
  nat_gateway_name: 'nat-gw-prod-eastus',
  public_ips: ['20.45.123.10', '20.45.123.11'],
  nodes: [
    {
      id: 'node-internet',
      label: 'Public Internet & SaaS Endpoints',
      type: 'internet',
      status: 'Healthy',
      details: {
        targets: ['api.stripe.com', 'login.microsoftonline.com', 'api.github.com'],
        policy: 'Requires whitelisted IP addresses for security firewalls',
      },
    },
    {
      id: 'node-pip',
      label: 'Public IP Addresses (Prefix / Single)',
      type: 'public_ip',
      status: 'Healthy',
      details: {
        ips: ['20.45.123.10', '20.45.123.11'],
        total_ports: 129024,
        ports_per_ip: 64512,
        sku: 'Standard IPv4 Static',
      },
    },
    {
      id: 'node-nat-gw',
      label: 'Azure NAT Gateway (nat-gw-prod-eastus)',
      type: 'nat_gateway',
      status: 'Healthy',
      details: {
        sku: 'Standard',
        zones: ['1', '2', '3'],
        idle_timeout: '4 minutes',
        tcp_reset: true,
        features: 'Dynamic SNAT port allocation, 50 Gbps throughput per gateway',
      },
    },
    {
      id: 'node-vnet',
      label: 'Virtual Network (vnet-prod-eastus)',
      type: 'vnet',
      status: 'Healthy',
      details: {
        cidr: '10.0.0.0/16',
        region: 'East US',
        resource_group: 'rg-networking-prod',
      },
    },
    {
      id: 'node-snet-frontend',
      label: 'frontend-subnet (10.0.1.0/24)',
      type: 'subnet',
      status: 'Healthy',
      details: {
        resources: 24,
        outbound_ip: '20.45.123.10',
        workloads: 'Nginx Ingress, Next.js Web Containers',
      },
    },
    {
      id: 'node-snet-backend',
      label: 'backend-subnet (10.0.2.0/24)',
      type: 'subnet',
      status: 'Healthy',
      details: {
        resources: 18,
        outbound_ip: '20.45.123.10',
        workloads: 'FastAPI Services, Order Processing, Payment Workers',
      },
    },
    {
      id: 'node-snet-database',
      label: 'database-subnet (10.0.3.0/24)',
      type: 'subnet',
      status: 'Healthy',
      details: {
        resources: 8,
        outbound_ip: '20.45.123.10',
        workloads: 'PostgreSQL Flexible Server, Redis Cache Replication',
      },
    },
    {
      id: 'node-snet-aks',
      label: 'aks-nodes-subnet (10.0.4.0/24)',
      type: 'subnet',
      status: 'Healthy',
      details: {
        resources: 32,
        outbound_ip: '20.45.123.11',
        workloads: 'Kubernetes Worker Nodes, DaemonSets, Telemetry Collectors',
      },
    },
  ],
  links: [
    { source: 'node-snet-frontend', target: 'node-nat-gw', label: 'Egress 0.0.0.0/0', flow_direction: 'outbound', active_flows: 428 },
    { source: 'node-snet-backend', target: 'node-nat-gw', label: 'Egress 0.0.0.0/0', flow_direction: 'outbound', active_flows: 512 },
    { source: 'node-snet-database', target: 'node-nat-gw', label: 'Egress 0.0.0.0/0', flow_direction: 'outbound', active_flows: 308 },
    { source: 'node-snet-aks', target: 'node-nat-gw', label: 'Egress 0.0.0.0/0', flow_direction: 'outbound', active_flows: 620 },
    { source: 'node-nat-gw', target: 'node-pip', label: 'SNAT Translation', flow_direction: 'outbound', active_flows: 1868 },
    { source: 'node-pip', target: 'node-internet', label: 'Deterministic Public Outbound', flow_direction: 'outbound', active_flows: 1868 },
  ],
  data_flow_explanation: [
    '1. Subnet instances (VMs, Pods) initiate outbound TCP/UDP connection toward internet destination (e.g. api.stripe.com:443).',
    '2. Azure SDN fabric directs outbound packets to the attached NAT Gateway rather than default internet egress or basic load balancer.',
    '3. NAT Gateway dynamically assigns an available SNAT port (1024-65535) from its configured Public IP pool (64,512 ports per IP).',
    '4. Packet leaves Azure with the stable public IP (20.45.123.10) as the Source IP and the assigned SNAT port as the Source Port.',
    '5. External service responds to 20.45.123.10:SNAT_PORT. NAT Gateway translates back to the private IP (e.g. 10.0.2.14) and delivers response packet seamlessly.',
  ],
};
